name: backend

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: myapp/backend

jobs:
  build:
    runs-on: [self-hosted, rhel]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.X
      
      - run: npm ci
      - run: npm run test -- --coverage
      - run: npm run build
      
      - name: 'Upload Coverage Artifact'
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: myapp/backend/coverage
          retention-days: 3

      - name: 'Upload Dist Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: myapp/backend/dist/index.js
          retention-days: 3